// ["EOF","PLUS","MINUS","TIMES","DIVIDE","LPAREN","RPAREN","NUMBER","ID","CLASS","NIL","ARRAY","WHILE","INT","VOID","EXTENDS","RETURN","NEW","IF","STRING","LBRACK","RBRACK","LBRACE","RBRACE","COMMA","DOT","SEMICOLON","ASSIGN","EQ","LT","GT"

public enum TokenTypeNames {
    EOF,
    PLUS,
    MINUS,
    TIMES,
    DIVIDE,
    LPAREN,
    RPAREN,
    INT,
    ID,
    CLASS,
    NIL,
    ARRAY,
    WHILE,
    TYPE_INT,
    TYPE_VOID,
    EXTENDS,
    RETURN,
    NEW,
    IF,
    STRING,
    LBRACK,
    RBRACK,
    LBRACE,
    RBRACE,
    COMMA,
    DOT,
    SEMICOLON,
    ASSIGN,
    EQ,
    LT,
    GT,
    TYPE_STRING
}